/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CheckBox {
    'label': string;
    'name': string;
    'selected': boolean;
  }
  interface GeneralRules {}
  interface RuleContainer {
    'heading': string;
    'subtitle': string;
  }
  interface RuleSection {
    'heading': string;
    'icon': string;
  }
  interface RulesTable {
    'columns': any[];
    'data': any[];
  }
}

declare global {


  interface HTMLCheckBoxElement extends Components.CheckBox, HTMLStencilElement {}
  var HTMLCheckBoxElement: {
    prototype: HTMLCheckBoxElement;
    new (): HTMLCheckBoxElement;
  };

  interface HTMLGeneralRulesElement extends Components.GeneralRules, HTMLStencilElement {}
  var HTMLGeneralRulesElement: {
    prototype: HTMLGeneralRulesElement;
    new (): HTMLGeneralRulesElement;
  };

  interface HTMLRuleContainerElement extends Components.RuleContainer, HTMLStencilElement {}
  var HTMLRuleContainerElement: {
    prototype: HTMLRuleContainerElement;
    new (): HTMLRuleContainerElement;
  };

  interface HTMLRuleSectionElement extends Components.RuleSection, HTMLStencilElement {}
  var HTMLRuleSectionElement: {
    prototype: HTMLRuleSectionElement;
    new (): HTMLRuleSectionElement;
  };

  interface HTMLRulesTableElement extends Components.RulesTable, HTMLStencilElement {}
  var HTMLRulesTableElement: {
    prototype: HTMLRulesTableElement;
    new (): HTMLRulesTableElement;
  };
  interface HTMLElementTagNameMap {
    'check-box': HTMLCheckBoxElement;
    'general-rules': HTMLGeneralRulesElement;
    'rule-container': HTMLRuleContainerElement;
    'rule-section': HTMLRuleSectionElement;
    'rules-table': HTMLRulesTableElement;
  }
}

declare namespace LocalJSX {
  interface CheckBox {
    'label'?: string;
    'name'?: string;
    'onCheckedChange'?: (event: CustomEvent<boolean>) => void;
    'selected'?: boolean;
  }
  interface GeneralRules {}
  interface RuleContainer {
    'heading'?: string;
    'subtitle'?: string;
  }
  interface RuleSection {
    'heading'?: string;
    'icon'?: string;
  }
  interface RulesTable {
    'columns'?: any[];
    'data'?: any[];
  }

  interface IntrinsicElements {
    'check-box': CheckBox;
    'general-rules': GeneralRules;
    'rule-container': RuleContainer;
    'rule-section': RuleSection;
    'rules-table': RulesTable;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'check-box': LocalJSX.CheckBox & JSXBase.HTMLAttributes<HTMLCheckBoxElement>;
      'general-rules': LocalJSX.GeneralRules & JSXBase.HTMLAttributes<HTMLGeneralRulesElement>;
      'rule-container': LocalJSX.RuleContainer & JSXBase.HTMLAttributes<HTMLRuleContainerElement>;
      'rule-section': LocalJSX.RuleSection & JSXBase.HTMLAttributes<HTMLRuleSectionElement>;
      'rules-table': LocalJSX.RulesTable & JSXBase.HTMLAttributes<HTMLRulesTableElement>;
    }
  }
}


